import { ChangeDetectionStrategy, Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-payment-receipt-invoice',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './payment-receipt-invoice.component.html',
  styleUrls: ['./payment-receipt-invoice.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class PaymentReceiptInvoiceComponent {
  leftMetaData = [
    {label: "Invoice No", value: "1234567890"},
    {label: "Party Name", value: "1234567890"},
    {label: "Party Address", value: "1234567890"},
    {label: "Party GST", value: "1234567890"},
    {label: "Place Of Supply", value: "1234567890"},
  ];

  rightMetaData = [
    {label: "Invoice Date", value: "1234567890"},
    {label: "State", value: "1234567890"},
    {label: "State Code", value: "1234567890"},
    {label: "Invoice Generated By", value: "1234567890"},
    {label: "Supply Type", value: "1234567890"},
  ]
}
